apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - pv.yaml
  - pvc.yaml
  - service.yaml
  - postgres_dep.yaml
  - redis_dep.yaml
  - docmost-configmap.yaml
  - docmost_dep.yaml
