apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: homelab
  labels:
    name: postgres
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
        egress: lan
        ingress: lan
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: postgres # https://github.com/postgres/postgres
          image: "postgres:16.8-alpine3.20" # 
          env:
            - name: POSTGRES_DB
              value: docmost
            - name: POSTGRES_USER
              value: docmost
            - name: POSTGRES_PASSWORD
              value: testPass123
          resources:
            limits:
              memory: "100Mi"
              cpu: "250m"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: postgres-data
          securityContext:
            allowPrivilegeEscalation: false
            # runAsUser: 1000
            # runAsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: docmost-local-config-pvc
