apiVersion: v1
kind: PersistentVolume
metadata:
  name: docmost-local-config-pv
  namespace: homelab
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: docmost-local-storage
  local:
    path: /path/to/dir
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - Node
