apiVersion: v1
kind: Service
metadata:
  name: docmost-svc
  namespace: homelab
  labels:
    name: docmost-svc
  annotations:
    name: docmost-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
      targetPort: http
      protocol: TCP
      # nodePort: 30000
  selector:
    name: docmost
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: homelab
  labels:
    name: postgres-svc
  annotations:
    name: postgres-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: http
      targetPort: http
      protocol: TCP
      # nodePort: 30000
  selector:
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: homelab
  labels:
    name: redis-svc
  annotations:
    name: redis-svc
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: http
      targetPort: http
      protocol: TCP
      # nodePort: 30000
  selector:
    name: redis
