apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-local-data-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: trilium-local-storage
  volumeName: trilium-local-data-pv
  resources:
    requests:
      storage: 2Gi
