#!/bin/bash

set -e

# By Chasercodeio.
#
# Inspiration:  Many articles that discuss importing images from dockerfiles
#               to kubernates use a registry. Either a public or private registry, this process
#               is cumbersome and overcomplicated. This script solves this issue by a simple pipeline:
#               | dockerfile to docker image -> export docker image to .tar -> import .tar image to kubernates |
#               There are a few hidden gotchas, so this script should help fix those too

# -- REQUIRED VARIABLES --

DEFAULT_K_SOCK="/run/k3s/containerd/containerd.sock" # This is the default k3s containerd socket. (first gotcha as ctr does not see this sock by default)
DEFAULT_K_NAMESPACE="k8s.io"                         # default namespace. (Second gotcha as without the kubernates socket, ctr does not show you this (More info on this in this README.md))
DEFAULT_DOCKER_TAR_OUTPUT="/tmp"                     # By default, the script will create the .tar file in the tmp dir and will delete in on restart
DEFAULT_DOCKER_TAR_OUTPUT_NAME="output.tar"
NAME_DOCKER_IMAGE=""
DOCKERFILE_PATH=""
DOCKERFILE_RM=false

# -- REQUIRED VARIABLES END --

help() {
  echo -e "Usage: ./dockerToKubeImage [-d <>][-p <>][-o <>][-s <>][-n <>][-r][-h] \n \t\t Options:"
  echo -e "\t\t\t [-d]: Docker image name:tag (required)"
  echo -e "\t\t\t [-p]: Path to dockerfile (can be relative) (required)"
  echo -e "\t\t\t [-o]: change docker image .tar file (Default: /tmp/) (optional)"
  echo -e "\t\t\t [-s]: The containerd runtime sock for kubernates (Default: /run/k3s/containerd/containerd.sock) (optional)"
  echo -e "\t\t\t [-n]: Default kubernates namespace (using containerd...different from "kubectl get namespace") (Default: k8s.io) (optional)"
  echo -e "\t\t\t [-r]: Remove the created image from docker images (default: false) (optional)"
  echo -e "\t\t\t [-h]: This help option"
}
# If run without any arguments
[ $# -eq 0 ] && help && exit 1

# If run without proper arguments
while getopts ":hd:p:o:s:rn:" flag; do
  case "${flag}" in
  h) help && exit 0 ;;
  o) # Can change the default output for docker tar file if wanting to save it somewhere (optional)
    DEFAULT_DOCKER_TAR_OUTPUT=${OPTARG} ;;
  d) # REQUIRED
    NAME_DOCKER_IMAGE=${OPTARG}
    ;;
  p) # REQUIRED
    DOCKERFILE_PATH=${OPTARG}
    ;;
  s) # optional
    DEFAULT_K_SOCK=${OPTARG}
    ;;
  n) # Optional
    DEFAULT_K_NAMESPACE=${OPTARG}
    ;;
  r) # Optional
    DOCKERFILE_RM=true
    ;;
  *) echo "Invalid option: -$OPTARG" && help ;;
  esac
done

# Make sure -n and -p are triggered and set b4 continuing
if [ "$NAME_DOCKER_IMAGE" == "" ]; then
  echo "-n <Name for the resulting docker image> is required"
  help
  exit 0
fi

if [ "$DOCKERFILE_PATH" == "" ]; then
  echo "-p <DockerFile path> is required"
  help
  exit 0
fi

# Make sure docker and ctr exist
if ! command -v docker 2>&1 >/dev/null; then
  echo "docker was not found on system, it is required..."
  exit 1
fi

if ! command -v ctr 2>&1 >/dev/null; then
  echo "ctr was not found on system, it is required..."
  exit 1
fi

# Now to the actual commands

# 1. Build dockerfile
docker build -t "$NAME_DOCKER_IMAGE" "$DOCKERFILE_PATH"

# 2. Export docker image to .tar file

docker image save -o "${DEFAULT_DOCKER_TAR_OUTPUT}/${DEFAULT_DOCKER_TAR_OUTPUT_NAME}" "$NAME_DOCKER_IMAGE"

# 2.5 Optional...if toggled... delete the resulting docker image from docker
if [ $DOCKERFILE_RM ]; then
  docker image rm "$NAME_DOCKER_IMAGE"
fi
# 3. Import .tar

sudo ctr -a "$DEFAULT_K_SOCK" -n "$DEFAULT_K_NAMESPACE" images import "${DEFAULT_DOCKER_TAR_OUTPUT}/${DEFAULT_DOCKER_TAR_OUTPUT_NAME}"
