apiVersion: v1
kind: Service
metadata:
  name: traggo-svc
  namespace: homelab
  labels:
    name: traggo-svc
  annotations:
    name: traggo-svc
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 3030
      name: http
      targetPort: http
      protocol: TCP
      nodePort: 30111
  selector:
    name: traggo
