apiVersion: v1
kind: PersistentVolume
metadata:
  name: metube-local-config-pv
  namespace: homelab
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: metube-local-storage
  local:
    path: /your/path/goes/here
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODENAME  
